### ISSUE TITLE
I can't bind the color in Shade to my selected item

### ISSUE THREAD

**Issue by AlonRom** [roubachof/Sharpnado.Shadows#10]
Hi,

for example, this doesn't work:

  <sh:Shade BlurRadius="10"
                      Opacity="0.5"
                      Offset="10,10"
                      Color="{Binding Color}" />

am I'm doing something wrong?

thanks

**Comment by roubachof** [comment]
ohoh, I maybe eer, maybe forgot to pass the `Shadows` `BindingContext` its `Shades`.
whoopsie.
Could you try the following and see if it works ?

```xml
<sh:Shade BlurRadius="10"
     BindingContext="{Binding YourModel}"
     Opacity="0.5"
     Offset="10,10"
     Color="{Binding Color}" />
```

Will fix this silly mistake quickly

**Comment by roubachof** [comment]
or you could do:

```xml
<sh:Shade BlurRadius="10"
     Opacity="0.5"
     Offset="10,10"
     Color="{Binding Source={RelativeSource AncestorType={x:Type local:YourModel}}, Path=Color}" />
```
It's just a workaround till waiting for the fix

**Comment by AlonRom** [comment]
@roubachof thanks, this - local:YourModel is my ViewModel?

**Comment by roubachof** [comment]
in the example with RelativeSource, it is your ViewModel type yes.

**Comment by AlonRom** [comment]
so it doesn't work, this is a selected item in a list.

**Comment by roubachof** [comment]
what is the name of your item ViewModel, and show me your xaml

**Comment by AlonRom** [comment]
Sure :)

<?xml version="1.0" encoding="UTF-8" ?>
<views:ViewContentBase
    x:Class="PetActivityMobile.Core.Views.DeviceSetup.DeviceLocate.DeviceLocateSetupLedColorView"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:border="clr-namespace:Syncfusion.XForms.Border;assembly=Syncfusion.Core.XForms"
    xmlns:customControls="clr-namespace:PetActivityMobile.Core.CustomControls;assembly=PetActivityMobile.Core"
    xmlns:gradient="clr-namespace:Syncfusion.XForms.Graphics;assembly=Syncfusion.Core.XForms"
    xmlns:local="clr-namespace:PetActivityMobile.Core.ViewModels.DeviceSetup.DeviceLocate;assembly=PetActivityMobile.Core"
    xmlns:scrControls="clr-namespace:PetActivityMobile.Core.CustomControls.ScrControls;assembly=PetActivityMobile.Core"
    xmlns:services="clr-namespace:Infra.Core.Services;assembly=Infra.Core"
    xmlns:sfList="clr-namespace:Syncfusion.ListView.XForms;assembly=Syncfusion.SfListView.XForms"
    xmlns:shades="clr-namespace:Sharpnado.Shades;assembly=Sharpnado.Shadows"
    xmlns:views="clr-namespace:PetActivityMobile.Core.Views.Base;assembly=PetActivityMobile.Core"
    Title="{Binding TextSource[Led]}"
    services:IOC.AutoWireViewModel="true"
    ShowMenuButton="false"
    ShowNavigateBar="true">
    <views:ViewContentBase.Resources>
        <ResourceDictionary>

            
            <DataTemplate x:Key="SelectedLedColorItemTemplate">
                <shades:Shadows
                    Margin="0,2,0,0"
                    BackgroundColor="White"
                    CornerRadius="40"
                    HeightRequest="70"
                    HorizontalOptions="Center"
                    WidthRequest="70">
                    <shades:Shadows.Shades>
                        <shades:ImmutableShades>
                            <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="5,5"
                                Color="{Binding Source={RelativeSource AncestorType={x:Type local:DeviceLocateSetupLedColorViewModel}}, Path=SelectedLed.Color}" />
                            <shades:Shade
                                BindingContext="{Binding}"
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="-5,-5"
                                Color="{Binding Source={RelativeSource AncestorType={x:Type local:DeviceLocateSetupLedColorViewModel}}, Path=SelectedLed.Color}" />
                            <shades:Shade
                                BindingContext="{Binding}"
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="-5,5"
                                Color="{Binding Color}" />
                            <shades:Shade
                                BindingContext="{Binding}"
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="5,-5"
                                Color="{Binding Color}" />
                        </shades:ImmutableShades>
                    </shades:Shadows.Shades>
                    <border:SfBorder
                        BorderColor="{StaticResource FiordColor}"
                        BorderWidth="3"
                        CornerRadius="25"
                        HeightRequest="50"
                        HorizontalOptions="Center"
                        ShadowColor="{StaticResource ShadowGrayColor}"
                        VerticalOptions="Center"
                        WidthRequest="50">

                        <gradient:SfGradientView BackgroundBrush="{Binding BackgroundGradient}" />
                    </border:SfBorder>
                </shades:Shadows>
            </DataTemplate>

            
            <DataTemplate x:Key="LedColorItemTemplate">
                <ContentView HeightRequest="70" WidthRequest="70">
                    <border:SfBorder
                        BorderColor="{StaticResource EntryBackgoundLite}"
                        BorderWidth="2"
                        CornerRadius="25"
                        HeightRequest="50"
                        HorizontalOptions="Center"
                        VerticalOptions="Center"
                        WidthRequest="50">
                        <gradient:SfGradientView BackgroundBrush="{Binding BackgroundGradient}" />
                    </border:SfBorder>
                </ContentView>
            </DataTemplate>
        </ResourceDictionary>
    </views:ViewContentBase.Resources>


    <StackLayout Margin="24">

        <scrControls:ScrLabel
            Margin="40,0"
            CustomFontFamily="SourceSansPro-Regular"
            FontSize="16"
            HorizontalOptions="CenterAndExpand"
            HorizontalTextAlignment="Center"
            Text="{Binding TextSource[Led_Explanation]}"
            TextColor="{StaticResource LableTextColor}"
            VerticalOptions="Start"
            VerticalTextAlignment="Center" />

        <Image
            Margin="0,30,0,0"
            Aspect="AspectFit"
            HorizontalOptions="FillAndExpand"
            Source="{customControls:ImageMultiResource PetActivityMobile.Core.Resources.locate-led-render}"
            VerticalOptions="CenterAndExpand" />

        <sfList:SfListView
            Margin="0"
            AutoFitMode="Height"
            HorizontalOptions="CenterAndExpand"
            IsScrollBarVisible="False"
            IsScrollingEnabled="False"
            ItemSize="70"
            ItemTemplate="{StaticResource LedColorItemTemplate}"
            ItemsSource="{Binding LedsColorList}"
            SelectedItem="{Binding SelectedLed}"
            SelectedItemTemplate="{StaticResource SelectedLedColorItemTemplate}"
            SelectionMode="Single"
            VerticalOptions="StartAndExpand">
            <sfList:SfListView.LayoutManager>
                <sfList:GridLayout SpanCount="4" />
            </sfList:SfListView.LayoutManager>
        </sfList:SfListView>
    </StackLayout>
</views:ViewContentBase>

**Comment by roubachof** [comment]
the type here:

```xml
AncestorType={x:Type local:DeviceLocateSetupLedColorViewModel}
```
should be your view model item type, not your parent view model. The one in your `LedsColorList`.

**Comment by AlonRom** [comment]
tried both of these and still nothing :/

   <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="5,5"
                                Color="{Binding Source={RelativeSource AncestorType={x:Type local:SelectedLed}}, Path=Color}" />
                            <shades:Shade
                                BindingContext="{Binding}"
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="-5,-5"
                                Color="{Binding Source={RelativeSource AncestorType={x:Type local:LedsColorList}}, Path=SelectedLed.Color}"

**Comment by roubachof** [comment]
lol no... not these one.
Ok then show me your `DeviceLocateSetupLedColorViewModel`.

**Comment by AlonRom** [comment]
Sure:

` public class DeviceLocateSetupLedColorViewModel : ViewModelBase
    {
        public DeviceLocateSetupLedColorViewModel()
        {
            InitializeLedColorList();
        }

        private LedColorModel _selecteLed;
        public LedColorModel SelectedLed
        {
            get => _selecteLed;
            set => SetProperty(ref _selecteLed, value);
        }

        private ObservableCollection<LedColorModel> _ledsColorList;

        public ObservableCollection<LedColorModel> LedsColorList
        {
            get => _ledsColorList;
            set => SetProperty(ref _ledsColorList, value);
        }

        public ICommand ContinueCommand =>
          new AsyncCommand(async () =>
          {
              await OnContinue();
          }, null);

        public override Task InitializeAsync(object navigationData)
        {
            AnalyticsAction(Consts.AnalyticsKeys.DeviceLocateSetupLedColorView);

            return base.InitializeAsync(navigationData);
        }

        private void InitializeLedColorList()
        {
            LedsColorList = new ObservableCollection<LedColorModel>
            {
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.GhostWhite),
                   BackgroundGradient = AddLinearGradient(Colors.SolideWhite, Colors.GhostWhite)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.PastelOrange),
                   BackgroundGradient=AddLinearGradient(Colors.PastelOrange, Colors.FadedOrange)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.LightMustard),
                   BackgroundGradient=AddLinearGradient(Colors.LightMustard, Colors.Maize)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.LightMossGreen),
                   BackgroundGradient=AddLinearGradient(Colors.LightMossGreen, Colors.TanGreen)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.AquaMarineTwo),
                   BackgroundGradient=AddLinearGradient(Colors.AquaMarineTwo, Colors.AquaMarine)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.DarkSkyBlue),
                   BackgroundGradient=AddLinearGradient(Colors.DarkSkyBlue, Colors.DarkSkyBlueTwo)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.Pink),
                   BackgroundGradient=AddLinearGradient(Colors.Pink, Colors.Bubblegum)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.Liliac),
                   BackgroundGradient=AddLinearGradient(Colors.Liliac, Colors.Periwinkle)
               }
            };
        }

        private SfLinearGradientBrush AddLinearGradient(string color1, string color2)
        {
            SfLinearGradientBrush gradient = new SfLinearGradientBrush();

            gradient.StartPoint = new Point(0, 0);
            gradient.EndPoint = new Point(1, 1);

            gradient.GradientStops.Add(new SfGradientStop() { Color = Color.FromHex(color1), Offset = 0 });
            gradient.GradientStops.Add(new SfGradientStop() { Color = Color.FromHex(color1), Offset = 0.5 });
            gradient.GradientStops.Add(new SfGradientStop() { Color = Color.FromHex(color2), Offset = 0.5 });
            gradient.GradientStops.Add(new SfGradientStop() { Color = Color.FromHex(color2), Offset = 1 });
            return gradient;
        }

        private async Task OnContinue()
        {
            //ToDo:
            //1. check ble permission
            //2. check tag connectivity ? 
            //3. save to tag
            //4. save to server
            //5. if error display error massage
            //6. navigate to ssids 

            await NavigationService.NavigateToAsync<DeviceLocateSetupSSIDsListViewModel>();
        }


        //ToDo:
        private Task SaveSensitivityLevelToTag()
        {
            return Task.CompletedTask;
        }

        //ToDo:
        private Task SaveSensitivityLevelToServer()
        {
            return Task.CompletedTask;
        }

        //ToDo:
        private Task ShowErrorDialog()
        {
            return Task.CompletedTask;
        }
    }

 public class LedColorModel : ExtendedBindableObject
    {
        public SfLinearGradientBrush BackgroundGradient { get; set; }
        //public Color Color { get; set; }

        private Color _color;
        public Color Color
        {
            get => _color;
            set => SetProperty(ref _color, value);
        }
    }

`

**Comment by roubachof** [comment]
ok then it's:

```xml
Color="{Binding Source={RelativeSource AncestorType={x:Type local:LedColorModel}}, Path=Color}"
```

**Comment by AlonRom** [comment]
still no:/ + there is a Xaml error

**Comment by roubachof** [comment]
Ok then it means we got the syntax wrong, juste give me a repro sample please.

**Comment by AlonRom** [comment]
ok.
Xaml:

`<?xml version="1.0" encoding="UTF-8" ?>
<views:ViewContentBase
    x:Class="PetActivityMobile.Core.Views.DeviceSetup.DeviceLocate.DeviceLocateSetupLedColorView"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:border="clr-namespace:Syncfusion.XForms.Border;assembly=Syncfusion.Core.XForms"
    xmlns:customControls="clr-namespace:PetActivityMobile.Core.CustomControls;assembly=PetActivityMobile.Core"
    xmlns:gradient="clr-namespace:Syncfusion.XForms.Graphics;assembly=Syncfusion.Core.XForms"
    xmlns:local="clr-namespace:PetActivityMobile.Core.Models.Device.DeviceLocate;assembly=PetActivityMobile.Core"
    xmlns:scrControls="clr-namespace:PetActivityMobile.Core.CustomControls.ScrControls;assembly=PetActivityMobile.Core"
    xmlns:services="clr-namespace:Infra.Core.Services;assembly=Infra.Core"
    xmlns:sfList="clr-namespace:Syncfusion.ListView.XForms;assembly=Syncfusion.SfListView.XForms"
    xmlns:shades="clr-namespace:Sharpnado.Shades;assembly=Sharpnado.Shadows"
    xmlns:views="clr-namespace:PetActivityMobile.Core.Views.Base;assembly=PetActivityMobile.Core"
    Title="{Binding TextSource[Led]}"
    services:IOC.AutoWireViewModel="true"
    ShowMenuButton="false"
    ShowNavigateBar="true">
    <views:ViewContentBase.Resources>
        <ResourceDictionary>

            
            <DataTemplate x:Key="SelectedLedColorItemTemplate">
                <shades:Shadows
                    Margin="0,2,0,0"
                    BackgroundColor="White"
                    CornerRadius="40"
                    HorizontalOptions="Center">
                    <shades:Shadows.Shades>
                        <shades:ImmutableShades>
                            <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="5,5"
                                Color="{Binding Source={RelativeSource AncestorType={x:Type local:LedColorModel}}, Path=Color}" />
                            <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="-5,-5"
                                Color="{Binding Source={RelativeSource AncestorType={x:Type local:LedColorModel}}, Path=Color}" />
                            <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="-5,5"
                                Color="{Binding Source={RelativeSource AncestorType={x:Type local:LedColorModel}}, Path=Color}" />
                            <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="5,-5"
                                Color="{Binding Source={RelativeSource AncestorType={x:Type local:LedColorModel}}, Path=Color}" />
                        </shades:ImmutableShades>
                    </shades:Shadows.Shades>
                    <border:SfBorder
                        BorderColor="{StaticResource FiordColor}"
                        BorderWidth="3"
                        CornerRadius="25"
                        HeightRequest="50"
                        HorizontalOptions="Center"
                        ShadowColor="{StaticResource ShadowGrayColor}"
                        VerticalOptions="Center"
                        WidthRequest="50">

                        <gradient:SfGradientView BackgroundBrush="{Binding BackgroundGradient}" />
                    </border:SfBorder>
                </shades:Shadows>
            </DataTemplate>

            
            <DataTemplate x:Key="LedColorItemTemplate">
                <ContentView>
                    <border:SfBorder
                        BorderColor="{StaticResource EntryBackgoundLite}"
                        BorderWidth="2"
                        CornerRadius="25"
                        HeightRequest="50"
                        HorizontalOptions="Center"
                        VerticalOptions="Center"
                        WidthRequest="50">
                        <gradient:SfGradientView BackgroundBrush="{Binding BackgroundGradient}" />
                    </border:SfBorder>
                </ContentView>
            </DataTemplate>
        </ResourceDictionary>
    </views:ViewContentBase.Resources>


    <StackLayout Margin="24" Spacing="0">

        <scrControls:ScrLabel
            Margin="20,0"
            CustomFontFamily="SourceSansPro-Regular"
            FontSize="16"
            HorizontalOptions="CenterAndExpand"
            HorizontalTextAlignment="Center"
            Text="{Binding TextSource[Led_Explanation]}"
            TextColor="{StaticResource LableTextColor}"
            VerticalOptions="Start"
            VerticalTextAlignment="Center" />

        <Image
            Margin="0,30,0,0"
            Aspect="AspectFit"
            HorizontalOptions="FillAndExpand"
            Source="{customControls:ImageMultiResource PetActivityMobile.Core.Resources.locate-led-render}"
            VerticalOptions="CenterAndExpand" />

        <sfList:SfListView
            HorizontalOptions="CenterAndExpand"
            IsScrollBarVisible="False"
            IsScrollingEnabled="False"
            ItemSize="75"
            ItemTemplate="{StaticResource LedColorItemTemplate}"
            ItemsSource="{Binding LedsColorList}"
            SelectedItem="{Binding SelectedLed}"
            SelectedItemTemplate="{StaticResource SelectedLedColorItemTemplate}"
            SelectionMode="Single"
            VerticalOptions="StartAndExpand">
            <sfList:SfListView.LayoutManager>
                <sfList:GridLayout SpanCount="4" />
            </sfList:SfListView.LayoutManager>
        </sfList:SfListView>

        <scrControls:ScrButton
            Margin="0,0,0,27"
            Command="{Binding NextCommand}"
            Style="{StaticResource ContinueButtonStyle}"
            Text="{Binding TextSource[General_Continue]}"
            VerticalOptions="End" />
    </StackLayout>
</views:ViewContentBase>
`

ViewModel:

`using System.Collections.ObjectModel;
using System.Threading.Tasks;
using System.Windows.Input;
using Infra.Core.Utils;
using PetActivityMobile.Core.Models.Device.DeviceLocate;
using PetActivityMobile.Core.ViewModels.Base;
using Syncfusion.XForms.Graphics;
using Xamarin.Forms;
using static PetActivityMobile.Core.Consts.AppConsts;

namespace PetActivityMobile.Core.ViewModels.DeviceSetup.DeviceLocate
{
    public class DeviceLocateSetupLedColorViewModel : ViewModelBase
    {
        public DeviceLocateSetupLedColorViewModel()
        {
            InitializeLedColorList();
        }

        private LedColorModel _selecteLed;
        public LedColorModel SelectedLed
        {
            get => _selecteLed;
            set => SetProperty(ref _selecteLed, value);
        }

        private ObservableCollection<LedColorModel> _ledsColorList;

        public ObservableCollection<LedColorModel> LedsColorList
        {
            get => _ledsColorList;
            set => SetProperty(ref _ledsColorList, value);
        }

        public ICommand ContinueCommand =>
          new AsyncCommand(async () =>
          {
              await OnContinue();
          }, null);

        public override Task InitializeAsync(object navigationData)
        {
            AnalyticsAction(Consts.AnalyticsKeys.DeviceLocateSetupLedColorView);

            return base.InitializeAsync(navigationData);
        }

        private void InitializeLedColorList()
        {
            LedsColorList = new ObservableCollection<LedColorModel>
            {
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.GhostWhite),
                   BackgroundGradient = AddLinearGradient(Colors.SolideWhite, Colors.GhostWhite)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.PastelOrange),
                   BackgroundGradient=AddLinearGradient(Colors.PastelOrange, Colors.FadedOrange)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.LightMustard),
                   BackgroundGradient=AddLinearGradient(Colors.LightMustard, Colors.Maize)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.LightMossGreen),
                   BackgroundGradient=AddLinearGradient(Colors.LightMossGreen, Colors.TanGreen)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.AquaMarineTwo),
                   BackgroundGradient=AddLinearGradient(Colors.AquaMarineTwo, Colors.AquaMarine)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.DarkSkyBlue),
                   BackgroundGradient=AddLinearGradient(Colors.DarkSkyBlue, Colors.DarkSkyBlueTwo)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.Pink),
                   BackgroundGradient=AddLinearGradient(Colors.Pink, Colors.Bubblegum)
               },
               new LedColorModel
               {
                   Color = Color.FromHex(Colors.Liliac),
                   BackgroundGradient=AddLinearGradient(Colors.Liliac, Colors.Periwinkle)
               }
            };
        }

        private SfLinearGradientBrush AddLinearGradient(string color1, string color2)
        {
            SfLinearGradientBrush gradient = new SfLinearGradientBrush();

            gradient.StartPoint = new Point(0, 0);
            gradient.EndPoint = new Point(1, 1);

            gradient.GradientStops.Add(new SfGradientStop() { Color = Color.FromHex(color1), Offset = 0 });
            gradient.GradientStops.Add(new SfGradientStop() { Color = Color.FromHex(color1), Offset = 0.5 });
            gradient.GradientStops.Add(new SfGradientStop() { Color = Color.FromHex(color2), Offset = 0.5 });
            gradient.GradientStops.Add(new SfGradientStop() { Color = Color.FromHex(color2), Offset = 1 });
            return gradient;
        }

        private async Task OnContinue()
        {
            //ToDo:
            //1. check ble permission
            //2. check tag connectivity ? 
            //3. save to tag
            //4. save to server
            //5. if error display error massage
            //6. navigate to ssids 

            await NavigationService.NavigateToAsync<DeviceLocateSetupSSIDsListViewModel>();
        }


        //ToDo:
        private Task SaveSensitivityLevelToTag()
        {
            return Task.CompletedTask;
        }

        //ToDo:
        private Task SaveSensitivityLevelToServer()
        {
            return Task.CompletedTask;
        }

        //ToDo:
        private Task ShowErrorDialog()
        {
            return Task.CompletedTask;
        }
    }
}

using Infra.Core.Base;
using Syncfusion.XForms.Graphics;
using Xamarin.Forms;

namespace PetActivityMobile.Core.Models.Device.DeviceLocate
{
    public class LedColorModel : ExtendedBindableObject
    {
        public SfLinearGradientBrush BackgroundGradient { get; set; }
        //public Color Color { get; set; }

        private Color _color;
        public Color Color
        {
            get => _color;
            set => SetProperty(ref _color, value);
        }
    }
}


`

**Comment by roubachof** [comment]
man this is not a repro sample, this is code. I need your whole solution zipped or shared on github.

**Comment by AlonRom** [comment]
sorry, this is not an option. this a production app.
is there something else that can help you help me?

**Comment by roubachof** [comment]
stay tuned, I will try something :)

**Comment by AlonRom** [comment]
thanks so much, biting my nails with anticipation.

**Comment by AlonRom** [comment]
Hi, do you have a workaround in the meantime? I really want to use this package.

**Comment by roubachof** [comment]
Hey, I'm currently fixing the issue, and I will release the package next week.
As soon as I fixed it in the code I will make a beta package for you, to see if it fixes your issue (should be today).

**Comment by AlonRom** [comment]
You are the best man!

**Comment by AlonRom** [comment]
thanks, how can I test it?

**Comment by themronion** [comment]
> thanks, how can I test it?
Either uninstall nuget and add the source files to your projects or wait for a new release

**Comment by AlonRom** [comment]
I prefer to use your official release, do you think that will be soon?

**Comment by themronion** [comment]
Well, @roubachof promised next week. So hold on)

**Comment by roubachof** [comment]
Please test the attached package (@themronion you can also test to see if you pr was correctly merged)

[Sharpnado.Shadows.1.1.0.nupkg.zip](https://github.com/roubachof/Sharpnado.Shadows/files/4909006/Sharpnado.Shadows.1.1.0.nupkg.zip)

**Comment by AlonRom** [comment]
> Please test the attached package (@themronion you can also test to see if your pr was correctly merged)
> 
> [Sharpnado.Shadows.1.1.0.nupkg.zip](https://github.com/roubachof/Sharpnado.Shadows/files/4909006/Sharpnado.Shadows.1.1.0.nupkg.zip)

Thanks, I've got a crash when I click on one of the items in the list:
"System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'Sharpnado.Shades.Droid.ShadowView'.'"

**Comment by roubachof** [comment]
Could I have the full stack trace please ?

**Comment by AlonRom** [comment]
> Could I have the full stack trace please ?

**Comment by AlonRom** [comment]
> > Could I have the full stack trace please ?

**Comment by AlonRom** [comment]
> > > Could I have the full stack trace please ?

Here is a link to a Sample Project: https://github.com/AlonRom/Sample.git
Once you click on the selected item it's crashing.
I have tested it on Galaxy S7 (herolte) (SM-G930F)

**Comment by roubachof** [comment]
Thanks for the feedback it helped a lot !

**Comment by AlonRom** [comment]
> Thanks for the feedback it helped a lot !

Sure :) will you release soon?

**Comment by roubachof** [comment]
new attempt.
[Sharpnado.Shadows.1.1.0.nupkg.zip](https://github.com/roubachof/Sharpnado.Shadows/files/4917789/Sharpnado.Shadows.1.1.0.nupkg.zip)

**Comment by AlonRom** [comment]
> new attempt.
> [Sharpnado.Shadows.1.1.0.nupkg.zip](https://github.com/roubachof/Sharpnado.Shadows/files/4917789/Sharpnado.Shadows.1.1.0.nupkg.zip)

sorry, still the same crash

**Comment by roubachof** [comment]
you need to clear your nuget cache before testing it, cause it has the same version as the previous one

**Comment by AlonRom** [comment]
> you need to clear your nuget cache before testing it, cause it has the same version as the previous one

can you release it, please?

**Comment by roubachof** [comment]
It won't change a thing for you if I release it, you still have an previous nuget package in your nuget cache. If you don't clear your local cache, it will not update the package.

**Comment by AlonRom** [comment]
> It won't change a thing for you if I release it, you still have a previous nuget package in your nuget cache. If you don't clear your local cache, it will not update the package.

not sure what you mean, I don't clean my cache when I update a nuget version.

**Comment by roubachof** [comment]
But you are not updating a nuget version in this case since this is the **same** version.
Anyway it's super easy, just delete this folder.

![image](https://user-images.githubusercontent.com/596903/87431324-c070f680-c5e6-11ea-934b-68d7203f55c7.png)

**Comment by AlonRom** [comment]
> But you are not updating a nuget version in this case since this is the **same** version.
> Anyway it's super easy, just delete this folder.
> 
> ![image](https://user-images.githubusercontent.com/596903/87431324-c070f680-c5e6-11ea-934b-68d7203f55c7.png)

I deleted, but I'm still getting error about 1.0.2:

Install-Package : NU1102: Unable to find package Sharpnado.Shadows with version (>= 1.1.0)
  - Found 3 version(s) in nuget-group [ Nearest version: 1.0.2 ]
At line:1 char:1
+ Install-Package C:\Users\CodeValue\Desktop\Sharpnado.Shadows.1.1.0.nu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'PetActivityMobile.Droid'.
At line:1 char:1
+ Install-Package C:\Users\CodeValue\Desktop\Sharpnado.Shadows.1.1.0.nu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by roubachof** [comment]
Put the unzipped package in a folder and add this folder as a local nuget storage.

**Comment by AlonRom** [comment]
> Put the unzipped package in a folder and add this folder as a local nuget storage.

cool, from the initial test looks great :) waiting for the official release.
appreciate the efforts!

**Comment by AlonRom** [comment]
@roubachof Hi, when will you publish the new package?

**Comment by Healios** [comment]
Just wanted to mention that I am also interested in the next version.

**Comment by roubachof** [comment]
Sharpnado.Shadows 1.1.0 has been released \o/

**Comment by PrajeetShrestha** [comment]
Hi I am on version 1.2.0, and still this issue persists. 

 **Error XFC0009: No property, BindableProperty, or event found for "Color", or mismatching type between value and property. (XFC0009)** 
 
`Color={Binding Source={RelativeSource AncestorType={x:Type vm:SomeViewModel}},  Path= EventBoxColor}}"`

**Comment by roubachof** [comment]
Sorry this is not the same issue

**Comment by PrajeetShrestha** [comment]
@roubachof So can you give me hints on how to solve this, BTW, I tried adding color with StaticResource in Xaml and it worked.
