### ISSUE TITLE
Received Error Messages after Installation

### ISSUE THREAD

**Issue by seansjames** [roubachof/Sharpnado.Shadows#17]
- OS:Both
 - Device: iPhoneSimulator & AndroidEmulator
 - Xamarin.Forms: 4.7.0.1239

After installation I received the following error message in "AppDelegate.cs" file:
The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)

1. Install Sharpnado.Shadows plugin from Nuget
2. Setup plugin in AppDelegate.cs file
3. Run emulator
4. Error message is produced

After uninstalling the plugin, the errors were resolved.

**Comment by roubachof** [comment]
Could you, at least, show me your AppDelegate code ?

**Comment by seansjames** [comment]
I was unable to replicate the issue after restarting my SDK and re-installing the plugin. 
I assume there must have been some system glitch during the last installation process.

The plugin works perfectly fine now.
