### ISSUE TITLE
Shadows degrade performance of ListViews/CollectionViews/SfListViews

### ISSUE THREAD

**Issue by Jerome-Liger** [roubachof/Sharpnado.Shadows#20]
First, thanks for this great feature, that enable us easy-development for nice UIs in XForms ;-)

The only problem we encounter with shadows, is that if we use them in DataTemplates/ItemTemplates, the lists have degraded performances and encounter some "lag" when scrolling...

Any maner to improve shadows better in ListViews ?
We tested it with ListViews, CollectionViews, SfListViews, Sharpnado.HorizontalListView, etc... the same "lag" everywhere, but if we just remove the shadows, the good performances are back again normaly...

Here attach some "Neumorphism UI" renders with Sharpnado.Shadows implemented... for Light and Dark Themes :-)
It will be great and soon in production if we can optimize these listview lags

![Screenshot_20200902-172817](https://user-images.githubusercontent.com/39192143/92004906-19d1e800-ed43-11ea-92c0-cea01265690f.jpg)

![Screenshot_20200902-172952](https://user-images.githubusercontent.com/39192143/92004924-1dfe0580-ed43-11ea-95c8-0c3a7796282c.jpg)

**Comment by roubachof** [comment]
Hey Jerome !
Nice UI ;)
Normally if all items have the same size (which seems to be your case), Shadows should be reused thanks to cell reuse.
You can have a look at this issue:  https://github.com/roubachof/Sharpnado.Shadows/issues/16
If you have still issues, you could share with me your app on a private repo and I could investigate :)

**Comment by Jerome-Liger** [comment]
Thanks for your quick return... and sorry for not having seen this issue, I missed it ;-)
I'll read it carrefuly, test some improvement mentionned, and get back to you quickly if It's not concluant (with sample or private repo).
I already know that I abused of Shadows... we put them everywhere ;-)

**Comment by Jerome-Liger** [comment]
Ok, did more tests and improve our lists, and Shadows don't realy have bad performance... I think it's normal to have some slowing with all these cells renders (it's more our using and abusing of it ;-))

Can close this issue.
Thanks

**Comment by kcrg** [comment]
@Jerome-Liger This could be the performance issue itself of the CollectionView. You can check out this blog post for some improvement tips: https://codetraveler.io/2020/07/12/improving-collectionview-scrolling/

**Comment by Jerome-Liger** [comment]
Thanks @kcrg , I'll have a look !
