### ISSUE TITLE
Improve Shadows performance on Android

### ISSUE THREAD

**Issue by roubachof** [roubachof/Sharpnado.Shadows#22]
I just implemented a `BitmapCache` for Android shadows.
It means that every shadows with the same properties (`Width/Height, Blur, Color, Opacity`), share the same `Bitmap` instance.
It should greatly improve the performance of Shadows in the list view.

Could some of you can Beta-test and tell me if you see improvements, and/or regressions?

@themronion 
@Jerome-Liger

[Sharpnado.Shadows.1.2.0-pre1.nupkg.zip](https://github.com/roubachof/Sharpnado.Shadows/files/5238151/Sharpnado.Shadows.1.2.0-pre1.nupkg.zip)

**Comment by Jerome-Liger** [comment]
Great, thanks !
I'll test it because we use the same shadows everywhere (in SfListView, CollectionView, Buttons, ContentViews,...)
I'll keep you in touch soon...

**Comment by Jerome-Liger** [comment]
New beta package tested and.... awsome !!!
The list are a way far very smoothier :-D
You can include this BitmapCache in the next package release... it's a must have !

Thanks a lot for this improvement (I keep the pre-1 in my project from now ;-) )

**Comment by themronion** [comment]
Wow cool! I will believe you and Jerome that they are major improvements. Keep up the fantastic work and waiting for the release!

**Comment by roubachof** [comment]
nah! dont wait for the release please test the nuget attached.
Add it in a local nuget repo:
https://www.c-sharpcorner.com/article/creating-a-local-nuget-package-repository/

And tell me all about it!

**Comment by themronion** [comment]
Oh okay, but the last time i tried a nuget it had issues on UWP, i forgot to tell u about them, the same issues as i fixed here #11, but i guess you erased my commented out lines with InternalLogger.Debug() and it breaked again. Can u please comment out those lines quickly or change all references to ActualSize and ActualOffset?

**Comment by roubachof** [comment]
The improvement is just for Android.
Also I can see your code here: https://github.com/roubachof/Sharpnado.Shadows/blob/master/Shadows/Shadows.UWP/UWPShadowsController.cs
(no more ActualSize.X ...)
So it doesn't seem to be erased...

**Comment by themronion** [comment]
Yeah, but still there are references in the InternalLogger: https://github.com/roubachof/Sharpnado.Shadows/blob/33b7b301ce028037f8ad95e9d3a55e4023be6026/Shadows/Shadows.UWP/UWPShadowsController.cs#L162

**Comment by roubachof** [comment]
argh or maybe this line: 
    InternalLogger.Debug(
                LogTag,
                $"shadowSource: {{ ActualOffset: {_shadowSource.ActualOffset}, ActualSize: {_shadowSource.ActualSize}, Margin: {_shadowSource.Margin} }}");

**Comment by themronion** [comment]
Yeah, yeah

**Comment by roubachof** [comment]
Zob as we say in france you're right. Wait, I will make a new pre package

**Comment by themronion** [comment]
)) Merci!!

**Comment by themronion** [comment]
meanwhile i tested it out on android - works faster indeed!! ListViews scroll faster than Musk's rockets)

**Comment by roubachof** [comment]
Thank you guys for tested it so quickly!

**Comment by roubachof** [comment]
@themronion here is the correction for uwp.
Could you please validate ?
[Sharpnado.Shadows.1.2.0-pre2.nupkg.zip](https://github.com/roubachof/Sharpnado.Shadows/files/5244762/Sharpnado.Shadows.1.2.0-pre2.nupkg.zip)

**Comment by themronion** [comment]
@roubachof  Nope((( Check the code, maybe there are still some references?

**Comment by roubachof** [comment]
Could you give me the full exception stack ? cant see anymore reference in uwp code...

**Comment by themronion** [comment]
Nevermind, after a complete cleaning, deleting and rebuilding the project it started to work as a charm!! Thanks!

**Comment by roubachof** [comment]
fixed by https://github.com/roubachof/Sharpnado.Shadows/releases/tag/v1.2.0
