### ISSUE TITLE
UWP Documentation

### ISSUE THREAD

**Issue by ninaada** [roubachof/Sharpnado.Shadows#23]
For UWP, assembly information needs to be included when the app is loading in app.xaml.cs. If this is not added, the app will throw some exceptions. This info is missing from the wiki, but the code is there in the samples. Attaching the screenshot of the line which I'm referring to. This would help anyone who might be facing this issue.
![image](https://user-images.githubusercontent.com/5279131/93563567-cb108900-f9a5-11ea-8067-ff5f54ae816c.png)

**Comment by themronion** [comment]
@ninaada Which error exactly are u getting? There are some issues in the nuget right now, @roubachof is taking care of them. Or after adding this line all issues were gone?

**Comment by ninaada** [comment]
@themronion I should add that this happens only in release mode. If not added, the compiler may not include the assembly. That's all.

**Comment by roubachof** [comment]
Well be added with the next push
