### ISSUE TITLE
[Bug][UWP] White Background added inside Shadow element when using SingleShade.

### ISSUE THREAD

**Issue by albertoha94** [roubachof/Sharpnado.Shadows#26]
**Platform (please complete the following information):**
 - OS: UWP
 - Device: Local Machine
 - Sdk version: 
    - Target Version: Windows 10, version 2004.
    - Min Version: Windows 10, version 1809.
 - Xamarin.Forms: 5.0.0.1709-pre4
 - Library version: 1.2.0

**Describe the bug**
While trying the library I came up with this background I couldn't remove inside UWP when implementing a SingleShade.
I have not tried other shades because I only wanted one.
Tried setting the property `BackgroundColor` to transparent in the Shadow element but didn't do anything.

**To Reproduce**
1. Create a new Xamarin.Forms project with Sharpnado.Shadows nuget installed in Android & UWP.
2. In your MainPage, add the following code:
```
<shadows:Shadows CornerRadius="20" Shades="{shadows:SingleShade Offset='5, 5', BlurRadius=10, Opacity=0.25, Color=Black}">
                            <shadows:Shadows.HorizontalOptions>
                                <OnPlatform x:TypeArguments="LayoutOptions">
                                    <On Platform="UWP" Value="Center" />
                                    <On Platform="Android" Value="Start" />
                                </OnPlatform>
                            </shadows:Shadows.HorizontalOptions>
                            <Label
                                FontSize="Large"
                                Text="This is a test Label"
                                VerticalOptions="Center" />
                        </shadows:Shadows>
```
3. Run both in Android & UWP.

The expected result is to see ONLY the shadow in both platforms.
In UWP the shadow does appear but it also adds a white background.

**Screenshots (if applicable)**
**Android:**
![screenshot-1607485895304](https://user-images.githubusercontent.com/14353851/101579679-d02b1600-399f-11eb-9d79-e26baf29f9d4.jpg)
**UWP:**
![image](https://user-images.githubusercontent.com/14353851/101579942-e3d67c80-399f-11eb-8b02-b723ef299ee7.png)

**Comment by roubachof** [comment]
This is a limitation of the way UWP handles shadows. It needs some sort of shape reference to create the shadows. In the process of creating the shadow, the shape reference (a rectangle with radius in our case) which is just under the child of our Shadows component cannot be hidden. And will show if you use a transparent color on Shadows. I tried a bit to create a shadow from scratch in UWP (without shadow api) but didn't have the time to implement it. So the workaround here is just to set a non transparent background color i in n UWP.

**Comment by albertoha94** [comment]
Thanks for the support roubachof.
I tried the workaround you mentioned but doesn't seem to work. Even though I set the `BackgroundColor` property, the white element remains.
**Android:**
![screenshot-1607580158521](https://user-images.githubusercontent.com/14353851/101728113-6a13c100-3a7b-11eb-8b07-cf7639bb042f.jpg)
**UWP:**
![image](https://user-images.githubusercontent.com/14353851/101728090-6122ef80-3a7b-11eb-9fb5-cbe036a72d1b.png)

**Comment by roubachof** [comment]
I mean you can't set the Shadows component background color to transparent unfortunately you can't have a shadow under the text of this on UWP...
