### ISSUE TITLE
Shade ColorBindableProperty is not Dynamic !

### ISSUE THREAD

**Issue by Jerome-Liger** [roubachof/Sharpnado.Shadows#27]
**Platform (please complete the following information):**
 - OS: [Both]
 - Devices: [iPhoneDevices/iPhoneSimulators/AndroidDevices/AndroidEmulators]
 - Sdk vervion: Whatever
 - Xamarin.Forms: [4.8.0.1451]

**Describe the bug**
When theming application (with LightTheme and DarkTheme for example), we need to apply "DynamicResources" to our visual elements, and when applying the theme, we just dynamically change the DynamicResources Values, and the application is themed automaticaly.

When I apply a "DynamicResource" to the "Color" property of a Sharpnado.Shade, it works for the first display, but when I change the value of my DynamicResource, it doesn't apply to the shade (it will do only if I reload completely the page, but it's not dynamic).

```
<sh:Shadows.Shades>
	<sh:ImmutableShades>
		<sh:Shade BlurRadius="3"
				  Opacity="1"
				  Offset="-4,-4"
				  Color="{DynamicResource DynamicNeumorphTopShadowColor}" />
		<sh:Shade BlurRadius="3"
				  Opacity="1"
				  Offset="4, 4"
				  Color="{DynamicResource DynamicNeumorphBottomShadowColor}" />
    </sh:ImmutableShades>
</sh:Shadows.Shades>
```

But the good news, is that I know why this behavior happens :

The "ColorProperty" (typeof(BindableProperty)) and the "Color" (typeof(Xamarin.Forms.Color)) are defining a type "Xamarin.Forms.Color" -> the Color type doesn't support/manage DynamicResources changes (it just convert the first call of our dynamicResource, to the current color associated)

To resolve this, you need to declare them as an "object" Type/returnType (and not a "Xamarin.Forms.Color" type) -> so we can give him a "DynamicResource" (in place of a static color) and when the value changes, it applies automagically ;-)

And maybe just ensure that this dynamic color changes is correctly managed in the "ElementPropertyChanged" methods of the platform renderers...

More info here -> [https://forums.xamarin.com/discussion/comment/378514/#Comment_378514](https://forums.xamarin.com/discussion/comment/378514/#Comment_378514)

**Screenshots (if applicable)**

Current behavior (Bad Shadows without page reload) :
![Wrong](https://user-images.githubusercontent.com/39192143/103356450-38f24380-4ab1-11eb-8bb5-ffd14ec4ccd4.png)

Expected behavior (Good Shadows after page reload) :
![Right](https://user-images.githubusercontent.com/39192143/103356350-f7619880-4ab0-11eb-8dcd-00dc28f6cbbf.png)

If I got enough time, I could do a PR... 
Let me know if you'll do it (or if you want a PR) for not doing the same work twice ;)

**Comment by robfrancis** [comment]
Also having this issue. Would appreciate the fix.

**Comment by roubachof** [comment]
Hi!
As you can tell, I have like zero times for this right now :)
So a PR could make it.

**Comment by robfrancis** [comment]
Try using 

Replace `<sh:ImmutableShades>` with `<shades:ShadeStack>`  

worked for me.

**Comment by roubachof** [comment]
@robfrancis is right `ImmutableShades` are... immutable x)

**Comment by roubachof** [comment]
will close this next week if no feedback is given.

**Comment by robfrancis** [comment]
close it. My issue that was the same was a human error 😂.
