### ISSUE TITLE
Very bad performance on Android

### ISSUE THREAD

**Issue by Tarekka** [roubachof/Sharpnado.Shadows#28]
**Platform (please complete the following information):**
 - OS: Android
 - Device: any Android device
 - Sdk vervion: Android SDK 29
 - Xamarin.Forms: 5.0.0.1874
 
**Describe the bug**
Really bad performance when using shadows.
I used one same immutable shadow defined in App.xaml resources, for 5 frames in a page, the UI freezes for ~4 seconds to load the page. iOS works perfectly.
Even with only one shadow object, it hangs a little to load the page.

**To Reproduce**
1. Create a view
2. Create an immutable shade like in the readme.
3. Apply the shade to some views

**Comment by roubachof** [comment]
Well you should be doing something wrong. Maybe have a look to the sample which scroll smoothly with more than 20 different shadows displayed. Of course can't do anything without a repro. Also did you use the latest version ?

**Comment by Huaba93** [comment]
Same problem here. I am using just one shadow and the entire page takes 1-2 MINUTES to render.

I will provide more infos soon

**Comment by roubachof** [comment]
Also, did you read : https://github.com/roubachof/Sharpnado.Shadows/blob/master/README.md#animating-shadows ?

**Comment by Huaba93** [comment]
@roubachof I think I was a little too hasty. atm I don't think shadows are causing my problems. It's more a forms 5 + AndroidX issue.

**Comment by roubachof** [comment]
yup always start by removing shadows and see if the issue is still there x)

**Comment by Huaba93** [comment]
@roubachof for me there is no problem with shadows ;)

**Comment by Tarekka** [comment]
@roubachof , thanks for your response.
I actually tried it in another one of my apps and it works perfectly. 
But in this app it takes time for some reason.

Any suggestions?
I'm using the latest version by the way, and I'm not animating anything.
Here's my example code:

App.xaml:
`<Style ApplyToDerivedTypes="True" TargetType="sh:Shadows">
                <Setter Property="CornerRadius" Value="10" />
                <Setter Property="Shades">
                    <sh:ImmutableShades>
                        <sh:Shade BlurRadius="50"
                      Opacity="1"
                      Offset="-10,-10"
                      Color="#80FFFFFF" />
                        <sh:Shade BlurRadius="50"
                      Opacity="1"
                      Offset="6, 6"
                      Color="#33000000" />
                    </sh:ImmutableShades>
                </Setter>
            </Style>`

One of the cells from my test page: 
`...
<sh:Shadows Grid.Column="0" Grid.Row="0" CornerRadius="20" StyleId="Note">
                        <sh:Shadows.GestureRecognizers><TapGestureRecognizer NumberOfTapsRequired="1" Tapped="TapGestureRecognizer_Tapped"/></sh:Shadows.GestureRecognizers>
                        <StackLayout BackgroundColor="#F0F0F3" Grid.Column="0" Padding="10" >
                            <Label Text="&#xf249;"
                                   TextColor="{StaticResource primary}"
                                   FontSize="40"
                                   FontFamily="{StaticResource FontAwesomeSolid}"
                                   HorizontalOptions="Center"
                                   HorizontalTextAlignment="Center"
                                   VerticalTextAlignment="Center"/>
                            <Label  Text="Note" HorizontalOptions="Center" HorizontalTextAlignment="Center"/>
                        </StackLayout>
                    </sh:Shadows>
...`

Output: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/46938523/104913914-397e4b80-5986-11eb-9c50-5b43f8160091.gif)

**Comment by roubachof** [comment]
sorry but:

1. your xaml is not even formatted: it's unreadable
2. shadows are costly to render so I guess when you are clicking the button, the view build time is causing this lag

You can either prerender your view then translate by the y axis when clicking the button.
Or use the LazyView on the "common" page, and call Load on the LazyView when the page is loaded:

https://www.sharpnado.com/xamarin-forms-lazyview-boost-your-app-reactivity-and-startup-time/
