### ISSUE TITLE
Colored Neumorphism

### ISSUE THREAD

**Issue by tatapuchi** [roubachof/Sharpnado.Shadows#29]
**Is your feature request related to a problem? Please describe.**
The neumorphism shades seem to only be for white, however I was thinking support for coloured neumorphism would be a really cool feature, because it looks really really cool as well: [Coloured Neumorphism](https://uxdesign.cc/neumorphism-can-we-make-it-more-accessible-15be5fe2ef28)

**Describe the solution you'd like**
The plugin could have colour support for the neumorphism shade, like blue for example in the aforementioned website.
![NeumorphButtons](https://user-images.githubusercontent.com/56786013/111684913-9764cd80-8827-11eb-8d47-12c155398aff.png)
![NeuButton2](https://user-images.githubusercontent.com/56786013/111684922-9af85480-8827-11eb-846f-f71a74da9cde.png)
![NeuButton3](https://user-images.githubusercontent.com/56786013/111684928-9c298180-8827-11eb-9c47-07b7ae8335cd.png)

These are some examples of coloured neumorphism, but I'm not really sure if this is going to be easy or hard to implement so this is more of just thoughts that a feature request I guess.

**Comment by kcrg** [comment]
I think it should basically change the shadow color in the upper left and lower right corners depending on the base color.
I do that in my app for the recruitment process, using the [neumorphism.io](https://neumorphism.io/) site. I can contribute to add support for that, imitating the behavior of this page shouldn't be troublesome, it's [open source](https://github.com/adamgiebl/neumorphism).

<table>
  <thead>
    <tr>
      <th>Dark</th>
      <th>Light</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><img src="https://raw.githubusercontent.com/kcrg/Minne/main/Screens/1.png" width="600" /></td>
      <td><img src="https://raw.githubusercontent.com/kcrg/Minne/main/Screens/2.png" width="600" /></td>
    </tr>
  </tbody>

**Comment by roubachof** [comment]
In fact "neumorphic" shadows are just regular shadows with just some precise properties.

        public NeumorphismShadesExtension()
        {
            _upperShade = new Shade
                {
                    BlurRadius = 10,
                    Opacity = 1,
                    Offset = new Point(-10, -10),
                    Color = Color.White,
                };

            _lowerShade = new Shade
                {
                    BlurRadius = 10,
                    Opacity = 1,
                    Offset = new Point(6, 6),
                    Color = LowerShadeColor,
                };
        }

You just have to test what color suits your need.
