### ISSUE TITLE
Java.Lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Symxn** [roubachof/Sharpnado.Shadows#3]
**Describe the bug**

Hi,

I have some pages in my app. On every page is a custom TitleBar, which I enclosed with your ShadowView so that it casts a shadow. Now I have noticed that after 30-40 pages have been created and rendered, an exception is thrown that the memory reserved for the app is full.

This only happens when I use your shadows. Apparently you are creating very large byte arrays for the shadows that are not cleared from memory quickly enough when navigating back and forth.

Can this problem be remedied?

**Exceptions (if applicable)**
```
Unhandled Exception:

Java.Lang.OutOfMemoryError: Failed to allocate a 2886412 byte allocation with 832368 free bytes and 812KB until OOM

**Comment by roubachof** [comment]
I need a repro sample to track down memory leaks (I love tracking down memory leaks :)

**Comment by roubachof** [comment]
Mmmh maybe I found something obvious...
Could you try with the attached nuget?

[Sharpnado.Shadows.1.0.1.nupkg.zip](https://github.com/roubachof/Sharpnado.Shadows/files/4781401/Sharpnado.Shadows.1.0.1.nupkg.zip)

**Comment by Symxn** [comment]
Yeah, the new version works. The exception no longer occurs. Now you can release version 1.0.1 for everyone. ;)
You are the best!

What have you changed now? (Only out of interest)

**Comment by ninaada** [comment]
Thanks for this amazing library! Is this fix published on nuget yet ?

**Comment by roubachof** [comment]
Not yet but very soon, tomorrow probably. But you can download the nuget  package above and if it fixes your issue

**Comment by roubachof** [comment]
package 1.0.1 was pushed on nuget: https://www.nuget.org/packages/Sharpnado.Shadows/1.0.1

**Comment by roubachof** [comment]
@Symxn I stupidly forgot to dispose the android ShadowView (which destroys bitmaps) in the Dispose method of renderer.
