### ISSUE TITLE
[Question] Adding shadow in Code Behind

### ISSUE THREAD

**Issue by AlleSchonWeg** [roubachof/Sharpnado.Shadows#31]
Hi,

what is the easiest/simplest way to add a SingleShade to a frame in code behind? Not xaml.

Thank you

**Comment by themronion** [comment]
```csharp
 forwardButton.Shades = new Shade[]
                {
                     new Shade
                    {
                        Color = Color.Black,
                        Opacity = 0.04,
                        Offset = new Point(0,5),
                        BlurRadius = 15
                    }
```

**Comment by AlleSchonWeg** [comment]
Thx,
i need to convert my existing Frame/Boxview/Grid etc. into a ShadowView?
I have a custom view which contains multiple elements. Some need a shadow, some don't.

**Comment by themronion** [comment]
ShadowView.Content = MyFrame

**Comment by AlleSchonWeg** [comment]
Thank you,

now i understand 👍
