### ISSUE TITLE
Shadow works only with iOS

### ISSUE THREAD

**Issue by AlleSchonWeg** [roubachof/Sharpnado.Shadows#32]
**Platform (please complete the following information):**
 - OS: [Android]
 - Device: [AndroidEmulator]
 - Sdk vervion: [Android SDK 28]
 - Xamarin.Forms: [5.0.0.2012]

**Describe the bug**
Shadow is draw with iOS, but not with Android. 

**To Reproduce**
1.  Run attached sample app with android and iOS

**Screenshots (if applicable)**
Android:
![android](https://user-images.githubusercontent.com/6727366/117283927-984ccf80-ae66-11eb-9942-6e021b4159fb.jpg)

iOS:
![ios](https://user-images.githubusercontent.com/6727366/117283967-a1d63780-ae66-11eb-8117-c44daad14376.jpg)

Sample App:
[Sharpnado.Shadows.Bug.zip](https://github.com/roubachof/Sharpnado.Shadows/files/6433760/Sharpnado.Shadows.Bug.zip)

**Comment by themronion** [comment]
Fix your layout. I haven't even launched the project but i already see that the problem is in your layout

**Comment by AlleSchonWeg** [comment]
What's the problem with the layout? The project is only repro sample.

**Comment by themronion** [comment]
i have no idea. Play around with it and u will get it working

**Comment by AlleSchonWeg** [comment]
Problem is the layout, but you have no idea what the problem is. This isn't realy helpful.

**Comment by roubachof** [comment]
I didn't looked at your layout but most of the time it's a padding issue. In android padding is clipping the children. So delete padding in parent element and add margin to the shadows and you should be fine 😀

**Comment by AlleSchonWeg** [comment]
Thank you. That helped me. 😀
