### ISSUE TITLE
Crash: ShadowView.CreateBitmap: java.lang.nullpointerException

### ISSUE THREAD

**Issue by InquisitorJax** [roubachof/Sharpnado.Shadows#36]
**Platform (please complete the following information):**
 - OS: Android
 - Device: Reports on galaxy Tab & Lenovo Tab
 - Sdk vervion: 9 & 10
 - Xamarin.Forms: Latest

**Describe the bug**
We're getting crash reports on ShadowView.CreateBitmap. Here's the stack trace from app center

**To Reproduce**
Haven't been able to repro locally - we're seeing these crash reports in App Center

**Exceptions (if applicable)**
[stack.txt](https://github.com/roubachof/Sharpnado.Shadows/files/7020326/stack.txt)
```
Unhandled Exception:
ShadowView.CreateBitmap (Sharpnado.Shades.Droid.ShadowView+ShadeInfo shadeInfo)
Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.renderscript.RenderScript.validate()' on a null object reference```

**Comment by InquisitorJax** [comment]
... just following up here - this is our XAML implementation:
```
<shades:ShadeStack>
	<shades:Shade BlurRadius="10"
	                         Opacity="0.05"
				 Offset="0,5"
				 Color="{DynamicResource DropShadowColor}" />	 
        <shades:Shade BlurRadius="12"
				 Opacity="0.05"
				 Offset="0,-5"
				 Color="{DynamicResource DropShadowColor}" />
</shades:ShadeStack>
```

**Comment by roubachof** [comment]
I have some time, I will try to add defensive code where the exception is raised.

**Comment by roubachof** [comment]
Last version should be more resilient
