### ISSUE TITLE
Shadow binding stopped working in 1.2.0 version (worked in 1.1.0)

### ISSUE THREAD

**Issue by AlonRom** [roubachof/Sharpnado.Shadows#39]
**Platform (please complete the following information):**
 - OS: Both
 - Device: all
 - Sdk vervion: all
 - Xamarin.Forms: Latest

**Describe the bug**
Shadow color binding stopped working in 1.2.0 version (worked in 1.1.0)

**To Reproduce**
Code:

       <sfList:SfListView
            Grid.Row="5"
            HorizontalOptions="CenterAndExpand"
            IsScrollBarVisible="False"
            IsScrollingEnabled="False"
            ItemSize="75"
            ItemTemplate="{StaticResource LedColorItemTemplate}"
            ItemsSource="{Binding LedsColorList}"
            SelectedItem="{Binding SelectedLed}"
            SelectedItemTemplate="{StaticResource SelectedLedColorItemTemplate}"
            SelectionMode="Single"
            VerticalOptions="StartAndExpand">
            <sfList:SfListView.LayoutManager>
                <sfList:GridLayout SpanCount="4" />
            </sfList:SfListView.LayoutManager>
        </sfList:SfListView>

      <DataTemplate x:Key="SelectedLedColorItemTemplate">
                <shades:Shadows
                    Margin="0,2,0,0"
                    BackgroundColor="White"
                    CornerRadius="40"
                    HorizontalOptions="Center">
                    <shades:Shadows.Shades>
                        <shades:ImmutableShades>
                            <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="5,5"
                                Color="{Binding ShadowColor}" />
                            <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="-5,-5"
                                Color="{Binding ShadowColor}" />
                            <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="-5,5"
                                Color="{Binding ShadowColor}" />
                            <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="5,-5"
                                Color="{Binding ShadowColor}" />
                        </shades:ImmutableShades>
                    </shades:Shadows.Shades>
                    <border:SfBorder
                        BorderColor="{StaticResource FiordColor}"
                        BorderWidth="3"
                        CornerRadius="25"
                        HeightRequest="50"
                        HorizontalOptions="Center"
                        ShadowColor="{StaticResource ShadowGrayColor}"
                        VerticalOptions="Center"
                        WidthRequest="50">

                        <gradient:SfGradientView BackgroundBrush="{Binding BackgroundGradient}" />
                    </border:SfBorder>
                </shades:Shadows>
            </DataTemplate>

Screenshots:
With 1.1.0:
![good](https://user-images.githubusercontent.com/27087135/169267044-b417a2f5-59b5-4f89-9400-bdc624631968.jpg)

With 1.2.0:
![bad](https://user-images.githubusercontent.com/27087135/169267026-41ca545e-f158-4df1-ada5-9f693216d46e.jpg)

**Comment by roubachof** [comment]
Hi 👋 
If you want to mutate shades use them in a stack of shades not in a immutable shades collection

**Comment by AlonRom** [comment]
@roubachof  do you have an example?
this exact code worked in the previous version.

**Comment by AlonRom** [comment]
@roubachof I changes to this:
   <shades:Shadows.Shades>
                        <shades:ShadeStack>
                            <shades:Shade
                                BlurRadius="10"
                                Opacity="0.3"
                                Offset="5,5"
                                Color="{Binding ShadowColor}" />
                                
and still not working on both platforms.

**Comment by roubachof** [comment]
Can you try to reproduce with the sample app ?

**Comment by AlonRom** [comment]
there you go:
https://github.com/AlonRom/ShadeBindingNotWorkingSample/tree/master/ShadeBindingNotWorkingSample

**Comment by AlonRom** [comment]
@roubachof did you have a chance to check?
I can go to the previous version if this is something you recommend, although I prefer to be updated as much as possible.

**Comment by AlonRom** [comment]
@roubachof  any chance to update regarding this issue?

**Comment by AlonRom** [comment]
@roubachof we are dependent on your package, can you please comment?

**Comment by roubachof** [comment]
![image](https://user-images.githubusercontent.com/596903/173526825-bfb28553-c34c-48dd-b7a9-141620783fd9.png)

**Comment by AlonRom** [comment]
@roubachof I removed the .nuget configuration file. can you please try again?

**Comment by roubachof** [comment]
Found the issue, however, since im not in a windows environnement I cannot make the nuget package...

**Comment by AlonRom** [comment]
@roubachof is it a matter of time? wait for it?

**Comment by AlonRom** [comment]
@roubachof ?

**Comment by roubachof** [comment]
Stay on the previous version until the release.

**Comment by AlonRom** [comment]
Do you have an estimate of when the next version will be published?

**Comment by AlonRom** [comment]
?

**Comment by AlonRom** [comment]
Hi @roubachof , I saw there is a 1.2.1. can you approve that the fix is included there?

**Comment by roubachof** [comment]
https://github.com/roubachof/Sharpnado.Shadows/releases

**Comment by AlonRom** [comment]
Hi @roubachof the issue is still not fixed in version 1.2.1

**Comment by roubachof** [comment]
I checked it with your sample
