### ISSUE TITLE
Maui support?

### ISSUE THREAD

**Issue by jasells** [roubachof/Sharpnado.Shadows#45]
Is there a plan/effort to port this package to Maui?

Would like to use this in a Maui App

**Describe alternatives you've considered**
None, yet.

**Comment by roubachof** [comment]
MAUI supports shadows, so I don't see the point porting this package.
But it would be rather easy, your could do a PR if you want :)

**Comment by jasells** [comment]
Ahh, ok that would explain why Sharpnado.Tabs doesn't have a dependency to a Maui-flavor of this one...  

Good to know, TY!

I would agree, if it is natively supported in Maui.. seems this is now OBE.

**Comment by roubachof** [comment]
exactly ;)
