### ISSUE TITLE
System.InvalidCastException on Windows

### ISSUE THREAD

**Issue by themronion** [roubachof/Sharpnado.Shadows#8]
Hey, it's me again! Wondering - this is a syncfusion issue or it is fixable by you somehow?
**Platform (please complete the following information):**
 - OS: Windows
 - Device: Windows PC
 - Sdk vervion: 10, 18362
 - Xamarin.Forms: Latest

**Describe the bug**
Description below, happens only on UWP, Android - fine, iOS - haven't tested but i guess it's ok.

**To Reproduce**
Install SFEffectsView and try to make it as a source for ShadowView:
`
<sh:Shadows...>
     <syncEffectsView:SfEffectsView...>
         <Frame.../>
   </syncEffectsView:SfEffectsView>
</sh:Shadows>
`

**Exceptions (if applicable)**
Copy paste the exception and the stack trace
```
System.InvalidCastException: "Unable to cast object of type 'Syncfusion.XForms.UWP.EffectsView.SfEffectsViewRenderer' to type 'Windows.UI.Xaml.IUIElement10'."
```

**Comment by themronion** [comment]
Update: not getting shadows at all, even without SfEffectsView. Maybe i've managed to break something :D

**Comment by themronion** [comment]
Fixed this issue and opened a pr #11

**Comment by roubachof** [comment]
hey man ty really much for the PR!
Would you be interested in fixing issue #8 for me ?
Doing that I will be able to release a new version quicker (hopefully next week)

**Comment by themronion** [comment]
The #11 pr is a fix for this issue

**Comment by roubachof** [comment]
lol yeah sorry I meant #9

**Comment by themronion** [comment]
I'll take a look, but as i remember i've compiled the source code sucessfully in x64

**Comment by roubachof** [comment]
I guess I put the x86 version in the nuget package. Should I put the x64 version instead?

**Comment by themronion** [comment]
Dunno man, dunno
