### ISSUE TITLE
UWP x64/x86 compilation

### ISSUE THREAD

**Issue by CrimsonFierce** [roubachof/Sharpnado.Shadows#9]
- OS: Windows
 - Device: Windows PC
 - Sdk vervion: 10.0.18363
 - Xamarin.Forms: Latest

**Describe the bug**
The UWP project cannot be compiled in x64

**To Reproduce**
1. Create a new Xamarin Forms projekt with UWP
2. Add NuGet Package Sharpnado.Shadows
3. Try to compile in x64

**Exceptions**
There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "C:\Users\Lars\.nuget\packages\sharpnado.shadows\1.0.2\lib\uap10.0.16299\Sharpnado.Shadows.UWP.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

**Comment by roubachof** [comment]
I don't really know how to resolve this....

**Comment by CrimsonFierce** [comment]
It seems that for UWP you only put the x86 version in the package. But since UWP doesn't know AnyCPU, you have to put the x86 and x64 version into the package.
Since I have never created my own package I don't know exactly, but it seems that both versions have to be referenced.
From what I've read it seems to happen in the file "Sharpnado.Shadows.nuspec", at least the data structure matches what I found:

https://stackoverflow.com/questions/35179461/adding-x86-and-x64-libraries-to-nuget-package

https://docs.microsoft.com/de-de/nuget/create-packages/supporting-multiple-target-frameworks

**Comment by roubachof** [comment]
There is something that I don't understand though. Xamarin. Forms package also only provide x86 dll. Don't you have the same issue with xf?

**Comment by CrimsonFierce** [comment]
I really don't know how Xamarin does it. 
I think it has something to do with the fact that Xamarin provides a lot of core and platform DLL's.

**Comment by roubachof** [comment]
I updated the `make-package.ps1` to build the x64 version of the UWP dll.
But I'm still confused on how to correctly write the nuspec in order to work on all UWP platforms. There are some discrepancies on different source of information and I'm not a UWP guys.
Could please try to correctly update the nuspec so it could work ?

**Comment by roubachof** [comment]
Should I put the x64 version for now ? I guess most of the win10 devices are x64 and not x86...

**Comment by roubachof** [comment]
With x64 uwp dll
[Sharpnado.Shadows.1.1.0.nupkg.zip](https://github.com/roubachof/Sharpnado.Shadows/files/4918001/Sharpnado.Shadows.1.1.0.nupkg.zip)

**Comment by CrimsonFierce** [comment]
Thank you, I'll try it.
I have created a Pull Request, but as I have not yet created a NuGet package I am not sure if this will have the desired effect.
So please test well.

**Comment by CrimsonFierce** [comment]
Das Paket funktioniert für x64, leider hat sich herausgestellt dass ich beide Plattformen brauche.
Ich habe ein Beispielprojekt gefunden, vielleicht hilft dir das weiter.

https://github.com/Cheesebaron/Nugetx86x64

**Comment by roubachof** [comment]
Sorry I don't have time for this issue right now. But I will gladly review PRs :)

**Comment by themronion** [comment]
For those who are expereincing this problem - just add the source files to the project instead of using nuget

**Comment by roubachof** [comment]
I'm still open to any PR on the matter: https://github.com/Cheesebaron/Nugetx86x64

**Comment by themronion** [comment]
Well, up to this moment this is the only valid solution)

**Comment by roubachof** [comment]
It would take the same time to solve the issue with a PR :)
And yes I am forcing it cause I want the users to be part of the project :)

**Comment by roubachof** [comment]
fixed by https://github.com/roubachof/Sharpnado.Shadows/releases/tag/v1.1.1
